// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamSlate.Data;

#nullable disable

namespace TeamSlate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamSlate.Models.BillableMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BillableMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Yes"
                        },
                        new
                        {
                            Id = 2,
                            Label = "No"
                        });
                });

            modelBuilder.Entity("TeamSlate.Models.DesignationMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DesignationMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tester"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tech Lead"
                        });
                });

            modelBuilder.Entity("TeamSlate.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BillableId")
                        .HasColumnType("int");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillableId");

                    b.HasIndex("DesignationId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = "100%",
                            BillableId = 1,
                            DesignationId = 1,
                            Name = "Khush Shah"
                        },
                        new
                        {
                            Id = 2,
                            Availability = "50%",
                            BillableId = 2,
                            DesignationId = 2,
                            Name = "Tom Parks"
                        },
                        new
                        {
                            Id = 3,
                            Availability = "75%",
                            BillableId = 1,
                            DesignationId = 1,
                            Name = "Charlie Brown"
                        },
                        new
                        {
                            Id = 4,
                            Availability = "100%",
                            BillableId = 1,
                            DesignationId = 3,
                            Name = "Kendall Roy"
                        },
                        new
                        {
                            Id = 5,
                            Availability = "40%",
                            BillableId = 2,
                            DesignationId = 3,
                            Name = "Tom Cruise"
                        },
                        new
                        {
                            Id = 6,
                            Availability = "90%",
                            BillableId = 1,
                            DesignationId = 2,
                            Name = "Elon Musk"
                        },
                        new
                        {
                            Id = 7,
                            Availability = "60%",
                            BillableId = 1,
                            DesignationId = 1,
                            Name = "George Clooney"
                        });
                });

            modelBuilder.Entity("TeamSlate.Models.ResourceSkill", b =>
                {
                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ResourceId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ResourceSkills");

                    b.HasData(
                        new
                        {
                            ResourceId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            ResourceId = 1,
                            SkillId = 2
                        },
                        new
                        {
                            ResourceId = 2,
                            SkillId = 3
                        },
                        new
                        {
                            ResourceId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            ResourceId = 4,
                            SkillId = 4
                        },
                        new
                        {
                            ResourceId = 5,
                            SkillId = 4
                        },
                        new
                        {
                            ResourceId = 6,
                            SkillId = 2
                        },
                        new
                        {
                            ResourceId = 6,
                            SkillId = 4
                        },
                        new
                        {
                            ResourceId = 7,
                            SkillId = 1
                        });
                });

            modelBuilder.Entity("TeamSlate.Models.SkillMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 3,
                            Name = "React"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Python"
                        });
                });

            modelBuilder.Entity("TeamSlate.Models.WeeklyHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("WeeklyHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hours = 40.0,
                            ResourceId = 1,
                            WeekStartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Hours = 20.0,
                            ResourceId = 2,
                            WeekStartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Hours = 30.0,
                            ResourceId = 3,
                            WeekStartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Hours = 40.0,
                            ResourceId = 4,
                            WeekStartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Hours = 16.0,
                            ResourceId = 5,
                            WeekStartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Hours = 36.0,
                            ResourceId = 6,
                            WeekStartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Hours = 24.0,
                            ResourceId = 7,
                            WeekStartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TeamSlate.Models.Resource", b =>
                {
                    b.HasOne("TeamSlate.Models.BillableMaster", "Billable")
                        .WithMany("Resources")
                        .HasForeignKey("BillableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamSlate.Models.DesignationMaster", "Designation")
                        .WithMany("Resources")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Billable");

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("TeamSlate.Models.ResourceSkill", b =>
                {
                    b.HasOne("TeamSlate.Models.Resource", "Resource")
                        .WithMany("ResourceSkills")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamSlate.Models.SkillMaster", "Skill")
                        .WithMany("ResourceSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("TeamSlate.Models.WeeklyHour", b =>
                {
                    b.HasOne("TeamSlate.Models.Resource", "Resource")
                        .WithMany("WeeklyHours")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("TeamSlate.Models.BillableMaster", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("TeamSlate.Models.DesignationMaster", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("TeamSlate.Models.Resource", b =>
                {
                    b.Navigation("ResourceSkills");

                    b.Navigation("WeeklyHours");
                });

            modelBuilder.Entity("TeamSlate.Models.SkillMaster", b =>
                {
                    b.Navigation("ResourceSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
